<template>
  <div
    class="relative w-screen h-screen overflow-hidden flex flex-col items-center justify-center text-white"
  >
    <div
      class="absolute inset-0 animate-gradient bg-[length:400%_400%] z-0"
    ></div>
    <div class="flex gap-6 mb-10 z-10">
      <div
        v-for="(icon, index) in icons"
        :key="index"
        class="text-2xl px-4 py-3.5 rounded-full bg-green-500/10 shadow-lg shadow-green-400/30 hover:scale-110 transition-all animate__animated animate__bounceInDown"
        :style="{ animationDelay: index * 0.05 + 's' }"
      >
        <font-awesome-icon :icon="icon" class="text-white" />
      </div>
    </div>
    <!-- Texto principal -->
    <div class="text-center space-y-2 tracking-in-expand z-10">
      <h1 class="text-3xl md:text-5xl font-extrabold focus-in-expand">
        Jared Garcia<br />
        <span
          class="bg-gradient-to-r from-green-800 via-green-400 to-green-600 bg-clip-text text-transparent focus-in-contract"
        >
          Frontend Developer
        </span>
      </h1>
      <p class="text-green-200/60 text-sm md:text-md">www.jaredgarcia.dev</p>
    </div>
  </div>
</template>

<script setup>
import { onMounted } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();

onMounted(() => {
  const target = sessionStorage.getItem("originalPath");

  setTimeout(() => {
    router.push(target || "/home"); // Si no hay ruta guardada, manda a /home
    sessionStorage.removeItem("originalPath");
  }, 3000);
});
const icons = [
  "fa-solid fa-code",
  "fa-solid fa-user",
  "fa-solid fa-laptop-code",
];
</script>

<style scoped>
@keyframes gradientMove {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
.animate-gradient {
  background: linear-gradient(-45deg, #0f0f0f, #013b1b, #0f0f0f, #025e2e);
  background-size: 300% 400%;
  animation: gradientMove 10s ease infinite;
  position: absolute;
  width: 100%;
  height: 100%;
  z-index: 0;
}

.tracking-in-expand {
  animation: tracking-in-expand 1s ease-in-out both;
}

@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

.focus-in-expand {
  -webkit-animation: focus-in-expand 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: focus-in-expand 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2025-4-13 14:45:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}

.focus-in-contract {
  -webkit-animation: focus-in-contract 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: focus-in-contract 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-4-13 14:44:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-contract
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-contract {
  0% {
    letter-spacing: 1em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes focus-in-contract {
  0% {
    letter-spacing: 1em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
.animate__animated {
  --animate-duration: 1s;
}
</style>
